### ISSUE TITLE
Grammar Error in layout-css page

### ISSUE THREAD

**Issue by dentonwong** [btholt/complete-intro-to-web-dev-v3#29]
(https://btholt.github.io/complete-intro-to-web-dev-v3/lessons/css/layout-css)

>inline – Like it sounds, it makes whatever the tag is behave like text. If you I want to style some text inline, this is how to do.

should be

>inline – Like it sounds, it makes whatever the tag is behave like text. If you want to style some text inline, this is how to do it.

-------------------------------

>Floats
The old, bullet-proof of laying things is using a property called float. The idea behind float is you'll an element to push itself as far left or right as possible, and once it's out of space, go to the next line.

Suggestion:

>Floats
The old, bullet-proof way of laying things out is by using a property called float. The idea behind float is that it allows an element to push itself as far left or right as possible, and once it's out of space, go to the next line.

**Comment by JAHANVI128** [comment]
I want to work on this issue
