### ISSUE TITLE
Grammar issue in css/grid

### ISSUE THREAD

**Issue by dentonwong** [btholt/complete-intro-to-web-dev-v3#31]
https://btholt.github.io/complete-intro-to-web-dev-v3/lessons/css/grid

>grid-template-column allows you you to set up how the grid is constructed. You can do it in percentages, pixels, or fr which stands for fractions. With with two 1fr we made it so each piece will take 50% of the space minus the gutters which it will calculate for you.

should be

>grid-template-column allows you you to set up how the grid is constructed. You can do it in percentages, pixels, or fr which stands for fractions. With two 1fr we made it so each piece will take 50% of the space minus the gutters which it will calculate for you.

**Comment by JAHANVI128** [comment]
I want to work on this issue
