### ISSUE TITLE
Trouble Accessing Individual Pages on Website

### ISSUE THREAD

**Issue by billythabrainy** [btholt/complete-intro-to-web-dev-v3#59]
I'm having trouble opening the individual pages on https://btholt.github.io/complete-intro-to-web-dev-v3. Every time I try, I get an error message saying 'Application error: a client-side exception has occurred'.

I noticed that if I turn off JavaScript, the website works fine, but when JavaScript is enabled, it doesn't work properly. I've tried opening it on different browsers like Edge and Firefox, and even on my phone with mobile data, but I still have the same problem.

In the browser console, I saw some error messages like 'A resource is blocked by OpaqueResponseBlocking' and 'TypeError: window.klipse is undefined'. I'm not even sure what these mean, i'm new at this😅, but it seems like there's an issue with the website.

Could someone please look into this? Thanks!

**Comment by 1Marc** [comment]
It's back up and running! Looks like the Klipse CDN went down, so we now are loading the script locally.

**Comment by billythabrainy** [comment]
Thank you soo much for getting back to me and fixing the problem! I'm just wondering, what's the Klipse CDN, and why did it stop working? And when you say you're loading the script locally now, what does that mean exactly? I'm trying to learn more about it all. Thanks again for your help!
