### ISSUE TITLE
open links in a new tab

### ISSUE THREAD

**Issue by Navynev** [btholt/complete-intro-to-web-dev-v3#66]
It would be helpful if the hyperlinks within the [Complete Intro to Web Development v3 course](https://btholt.github.io/complete-intro-to-web-dev-v3/lessons/welcome-to-the-class/intro) could open in a new tab. This would improve user experience by allowing users to open resources without navigating away from the course content. Otherwise, it's pretty annoying ^^

Thank you for considering this request!
Nev

**Comment by dtauer** [comment]
Yes, would be a nice feature, but links are currently generated with Markdown.
